### ISSUE TITLE
Unable to open prices existing proof

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#1051]
### What
Trying to edit an existing proof using the `?proof_id=` URL parameter on `/prices/add/multiple` results in:
`TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.`

### Steps to reproduce the behavior:
1. Open an exsisting on the add price page or try to edit one on `/proofs/{id}`
2. The page will just load the normal `Add multiple prices` model
3. The console shows the error

### Expected behavior
Should show the previously added prices for the proof (if any) and load the proof image.

### Screenshots
![Image](https://github.com/user-attachments/assets/27792fa4-ab3e-46d6-953c-5d1d95c65c00)

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Windows 10
 - Platform: Desktop

### Part of
-

**Comment by raphodn** [comment]
Thanks for the bug report 🙏 
Following #1043
I fixed it last night : https://github.com/openfoodfacts/open-prices-frontend/commit/40301dc00b4a094b6ff0b9bccdb36d63bc0c1807
