### ISSUE TITLE
Contribution Assistant - Category is not selected anymore

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#1104]
### What

When using the contribution assistant on "raw" products, the "category" toggle and the category name is not pre-filled anymore. It looks like it's a regression from previous version.

![Image](https://github.com/user-attachments/assets/176764e3-a243-4e3f-b29b-6c0c05440fc0)

**Comment by raphodn** [comment]
Most likely my fault i made some susbstantial changes on the different form fields.

I tried this afternoon with barcodes and it worked great. Will check for the category, should be a quick fix
