### ISSUE TITLE
New page that lists all Price tag proofs without any prices yet (= open for contribution)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#1115]
### Story

Following changes in the backend - https://github.com/openfoodfacts/open-prices/issues/568 - users are now allowed to add prices on PRICE_TAG proofs they do now own. Thus unlocking distributed contribution.

To kickstart this, we need a page that lists all available proofs open for contribution.

### How

A list of all proofs that have the following caracteristics:
- type = PRICE_TAG
- price_count = 0
- location_id__isnull = False

And clear actions for each proof : 
- view full size image
- add prices
- add prices via the contribution assistant

### Questions

- how to avoid users adding prices on the same proof ?
- how to skip proofs that are unreable or without any barcodes displayed ? 
  - allow users to tag proofs ?

### Ideas

- display proofs in a random order on each load, to mitigate the risk of having 2 users simultaneously adding prices on the same proof

**Comment by raphael0202** [comment]
Displaying proofs at random is enough for now! We should just keep in mind that SQL random() doesn't scale well to huge tables (as seen on Robotoff).
I wonder whether it's better to wait for https://github.com/openfoodfacts/open-prices/issues/611 to be implemented in the backend, as it will make it easier from a front-end perspective:
- fetch the `price_tag`s with `status=null` randomly
- annotate (using an interface similar to the 3rd step from the contribution assistant)
- repeat

Another game could be to check that no bounding box (=item in the `price_tag` table) is missing, and if there are some, the user draw additional bounding boxes, which become available as new `price_tag`s items to annotate.

**Comment by raphodn** [comment]
I think in the meantime I'll just do a "Latest proofs" page

**Comment by raphodn** [comment]
closing as we'll wait for "prices to validate list" instead of this "proofs to add list"
