### ISSUE TITLE
Dashboard: Proof card: PriceCountChip: misleading colors

### ISSUE THREAD

**Issue by k127** [openfoodfacts/open-prices-frontend#1187]
### What
As a user, you may find the colour coding of the price count chip misleading, used on the respective component: https://github.com/openfoodfacts/open-prices-frontend/blob/580ea071e34bdbc474452e7aed37f2a726302172/src/components/PriceCountChip.vue#L22-L33

While in other contexts such as [PriceCard.vue](https://github.com/openfoodfacts/open-prices-frontend/blob/master/src/components/PriceCard.vue), the same coloring algorithm may be meaningful, it appears not to be in the context of [ProofFooterRow.vue](https://github.com/openfoodfacts/open-prices-frontend/blob/master/src/components/ProofFooterRow.vue).

### Steps to reproduce the behavior:
1. Have some proofs available with zero, one, and more than one prices
2. Visit <https://prices.openfoodfacts.org/dashboard/proofs>
3. Inspect the PriceCountChip within a ProofCard

### Expected behavior
Finding a more meaningful color coding that also respects `proof.receipt_price_count`, in addition to `proof.price_count`:
```js
      // symbols are pseudo named
      if (this.price_count === 0) {
        return 'error'
      }
      else if (this.price_count < this.receipt_price_count) {
        return 'warning'
      }
      else if (this.price_count === this.receipt_price_count) {
        return 'success'
      }
      else if (this.price_count > this.receipt_price_count) {
        return 'error'
      }
```
A determination of whether the _PriceCountChip_ component is used in _PriceCard_, or _ProofFooterRow_, would also be required.

**Comment by raphodn** [comment]
Indeed the ProofCard price color should be green when at least 1 price is linked, doesn't make sense to have the intermediate yellow color.

![Image](https://github.com/user-attachments/assets/ac54a2c9-29e9-43db-ba11-f53111740e1b)

**Comment by raphodn** [comment]
Regarding the "consumption-related fields" (receipt_price_count), it's not always equivalent to the price_count, for instance if you buy multiple quantities of the same item. so it's tricky right now to have a hard rule. see #1169
