### ISSUE TITLE
Add a link to the proof card to complete prices using the contribution assistant

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#1194]
Adding a "Complete with the contribution assistant" option here would help a lot:

![Image](https://github.com/user-attachments/assets/6762c796-4f68-4fcf-b79c-e16d0ea43c00)

**Comment by raphael0202** [comment]
It would be awesome to also have the link in https://prices.openfoodfacts.org/proofs!

**Comment by raphodn** [comment]
> It would be awesome to also have the link in https://prices.openfoodfacts.org/proofs!

I believe there is, no ? Only for your proofs at the moment

**Comment by raphael0202** [comment]
I meant for all proofs.

**Comment by raphodn** [comment]
Linked: in #1220 I added in the Price card action menu a direct link to the proof's detail page
