### ISSUE TITLE
Raw category doesn't show newly added product

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#1205]
### What

I added a price of a raw product of category `en:roasted-hazelnuts`: https://prices.openfoodfacts.org/proofs/14701

When clicking on the "product name", there are 0 prices: https://prices.openfoodfacts.org/products/en:roasted-hazelnuts

**Comment by raphodn** [comment]
My bad, linked to this commit: https://github.com/openfoodfacts/open-prices-frontend/commit/7e3a0468b095858beb6d8099d33d51a6d179f2fc

The ProductDetail isn't correctly setup so it's failing to fetch prices.
