### ISSUE TITLE
Disable the done button is no price added

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/open-prices-frontend#222]
When you upload a receipt, it's not obvious you need to add prices on by one. I though pressing "done" would lead me to a new step scan articles.  This button should be disabled if no price is attached to the proof

**Comment by raphodn** [comment]
Hi ! Yeah you're right :+1: 

(though in the future we might allow separating proof upload and price upload, allowing users to come back to an uploaded proof and adding prices related to it)
