### ISSUE TITLE
Translate raw product categories

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#224]
### Story

Currently the list of categories is only limited to english : https://github.com/openfoodfacts/open-prices-frontend/blob/master/src/data/category-tags.json

See #30 on how it was initiated

the full json is here : https://static.openfoodfacts.org/data/taxonomies/categories.full.json

**Comment by raphodn** [comment]
Currently the `categories-tags.json` is only a subset of all the categories. We could add the available translations in english.

@raphael0202 did the filtering. Could you share your script ? So that we can use it to add the other languages ?

**Comment by raphael0202** [comment]
I built it manually by fetching children of "fruits", "vegetables" and selecting them.
If we use the autocomplete feature of search-a-licious, we won't be able to have this filtered set of categories.
One quicker way of doing this would be to add all translations to the JSON file. The full category taxonomy in JSON is not that big, so with a reduced set I think it's a reasonable approach.

**Comment by raphodn** [comment]
@raphael0202 did you have a look at the script to filter the raw categories + translate them ? 
- script here : https://github.com/openfoodfacts/open-prices-frontend/blob/master/data/categories/filter_categories.py
- additional filtering or categories needed ?
- should this (script & jsons) be in the frontend, or in the backend ?

**Comment by raphael0202** [comment]
It looks good to me!
Keeping it front-end is good to me as long as the bundle size is reasonable.
