### ISSUE TITLE
Improve welcome instruction

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/open-prices-frontend#225]
I tried to run the front, then realized I need to run the back, and then struggled with the intallation instruction.

For Poetry, you have to install the `v1.6.1` Otherwise it refuse to install the project:  https://github.com/python-poetry/poetry/issues/8662#issuecomment-1866886564

And the next command returns an error ending with 

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
```

Running `sudo docker compose up` is easier to have the server running, but from here, I get the following error. I assume it's because I did not run `poetry run alembic upgrade head` but I don't know where to run it 

```
open_prices-api-1        | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "prices" does not exist
open_prices-api-1        | LINE 3: FROM prices) AS anon_1
```

**Comment by raphodn** [comment]
Hi Alex, indeed we haven't done much regarding the dev documentation

did you manage to get it running ? I don't use Docker in local, so I'm not really sure what is the exact setup for that. Don't hesitate to open a PR I'll be happy to merge :)

**Comment by raphael0202** [comment]
> Running sudo docker compose up is easier to have the server running, but from here, I get the following error. I assume it's because I did not run poetry run alembic upgrade head but I don't know where to run it

A `make migrate-db` will do as well

**Comment by alexfauquette** [comment]
> A make migrate-db will do as well

Thanks, that solves my issue, now the project is running :tada: 

Just on note if others are reading this issue: You might receive the following error:
```
make: docker-compose: No such file or directory
make: *** [Makefile:139: migrate-db] Error 127
```

That's because if you use latest version of dockers you need to apply the following diff to the MAKE file:

```diff
- docker-compose
+ docker compose
```

**Comment by raphael0202** [comment]
Great! Feel free to submit a PR to update the instructions :)

**Comment by alexfauquette** [comment]
> Great! Feel free to submit a PR to update the instructions :)

Yep, that's planned for tonight (after working day)
