### ISSUE TITLE
Add direct one-click links to the web interface to direct view/edit products on the main OFF database for which one has added own prices

### ISSUE THREAD

**Issue by fabi003** [openfoodfacts/open-prices-frontend#253]
I scanned a bon and entered some prices on the web interface and want to edit the products with missing data e.g. they have no photo or are not in the database, later after I have taken some pictures or have time to add them. So it would be useful to have not to click on a single product first on https://prices.openfoodfacts.org/app/dashboard/prices to have the possibility to go direct to OFF. This may also be useful for views on other price pages.

**Comment by teolemon** [comment]
Probably, 
- a link to the Open Food Facts user account: https://world.openfoodfacts.org/cgi/user.pl?type=edit&userid=teolemon
- a link to edit mode: https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=4016249207021

**Comment by fabi003** [comment]
If it is unclear, I mean a direct edit-link for the product.

**Comment by raphodn** [comment]
If you go on a product detail page - e.g. https://prices.openfoodfacts.org/app/products/8000500329474 - there is a direct link to the OFF product.

In the product list page, adding a button with a direct link on each "product card" might be a bit overloading the page, maybe a settings to display it ?

![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/11ccdef9-e2e2-4537-b3d8-4460492daac6)

**Comment by fabi003** [comment]
An configuration option, which is off by default, would be OK, if you think it is overloading or clicked by accident. I added my first bon and had three new products and a few others without picture or other issues and, at least for me, it would be useful not to have to select the product first to go to the OFF main product page. It saves some clicks/page loading for such bon bulk edits.

**Comment by fabi003** [comment]
As it is now there, it is OK, if the website would not lose you viewing context. As you have to hit "load more" again, when you go back via the browsers back-button, which is a problem, when you don't have the time to do instant edits after uploading prices.

I also hope that it is planned to save the options to the account settings in the future, as I delete any cookies at the end of the browser session.
