### ISSUE TITLE
Raw / bulk products: add missing categories

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#262]
### Story

Following #30 & #87

https://raw.githubusercontent.com/openfoodfacts/openfoodfacts-server/main/taxonomies/food/categories.txt

Some categories in the price category choices are missing :
- brocoli, chou fleur ?
- meat
- eggs
- fish...

And some categories need to be removed : 
- canned
- frozen

**Comment by raphodn** [comment]
- patate douce

**Comment by serpico** [comment]
- foie de poulet , while there might be an [EAN](https://world.openfoodfacts.org/product/0226015011286/foies-de-poulet#) when it's prepackeged the quantity always vary slightly so input the price par quantity seems more appropriate
- saucisses savoyardes
- saucisses au roquefort
- saucisses piment / saucisses au piment
- saucisses aux herbes
- saucisses chèvre miel
- merguez
- chipolatas
- chair à saucisse
- chair à tomate

**Comment by aleene** [comment]
I assume these are missing from the selection on Prices. We could add a special parent category to the taxonomy for products that are sold per weight (fresh vegetables, etc,) and individually (croissant, baguette, hot coffee, etc). And where weight is more appropriate (EAN with multiple weight/prices).

**Comment by serpico** [comment]
Is there a way to displays all the available types of pomme de terre/pommes de terre available regardless of which one of those 2 spellings the user type ? Currently :

- `pommes de terre` displays 14 variations/choices
- `pomme de terre ` displays 5 variations/choices

**Comment by raphodn** [comment]
fyi the current list of categories is here (a folder, with 1 file per language code) : https://github.com/openfoodfacts/open-prices-frontend/tree/master/src/data/categories

it is generated after running this script : https://github.com/openfoodfacts/open-prices-frontend/blob/master/data/categories/filter_categories.py
see PR #273 for more details

for filtering component we use : https://vuetifyjs.com/en/components/autocompletes/
not sure if it manages "fuzzy" search easily

**Comment by aleene** [comment]
Thanks for the list. I will relove some.

**Comment by aleene** [comment]
The list has many errors as the synonyms have been included.

**Comment by raphodn** [comment]
Fyi i put this list for information, but the script that filters the categories only selects a subset of these. So in the Prices app there isn't as many categories thankfully :)

**Comment by aleene** [comment]
I could add the parameter `sales-format` to entries in the category taxonomy. This could have values `package`, `item` or `weight`. The parameter is inheritable, so at a node, implies all children have the same values. A child could overrule maybe. I could start adding these based on the categories you already identified.

**Comment by raphodn** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/pull/10412

**Comment by serpico** [comment]
@aleene is it possible to add "Pain de semoule" with "Kesra" and "Matlou" as synonims to https://github.com/openfoodfacts/openfoodfacts-server/blob/main/taxonomies/food/categories.txt ?

@raphodn https://github.com/openfoodfacts/open-prices-frontend/issues/262 included `en:breads` in the filter so it should show up in the availaible choice once added right ?

![paindesemoule](https://github.com/user-attachments/assets/5c03d93f-5f0f-4937-8abe-6361cd374d41)

**Comment by raphodn** [comment]
Also, Justin told me yesterday that "Potimaron" was missing

**Comment by aleene** [comment]
Should be in de pipeline.

**Comment by raphodn** [comment]
Justin : missing 
- patate douce
- maïs

**Comment by raphodn** [comment]
closing in favor of #1048 (duplicate issue)
@raphael0202 can you check if there is some missing categories here ?

**Comment by raphael0202** [comment]
I added the missing one to #1048, thanks!

**Comment by raphodn** [comment]
PR #2 of the idea of the `sales_format` field: https://github.com/openfoodfacts/openfoodfacts-server/pull/11347

**Comment by raphodn** [comment]
In this PR - https://github.com/openfoodfacts/openfoodfacts-server/pull/11199 - it seems the `sales_format` was added to almost 300 categories !
