### ISSUE TITLE
Store list of locales and update when new are added or perform regular check

### ISSUE THREAD

**Issue by dq18** [openfoodfacts/open-prices-frontend#263]
### Problem
Currently, the list of locales is computed when mounting the UserSettings page and forces a mounted async. This list is created by checking the `{locales}.json` files. Since the addition of a new language will be rare, this computation could be avoided.

### Proposed solution
It would be preferable to have a list stored in a json file that regularly updates or updates on event.

**Comment by raphodn** [comment]
There's also the translation completion percentage which we could pre-calculate

**Comment by dq18** [comment]
This would need the personal access token for Crowdin API. I am not sure how it works and if it is possible not to have it shared in an open-source project. But if possible, would be glad to be able to use the Crowdin API

**Comment by raphodn** [comment]
Done in https://github.com/openfoodfacts/open-prices-frontend/pull/338 ?

**Comment by dq18** [comment]
I think we can close it. The pure automation part will come later if needed

**Comment by dq18** [comment]
Closed

**Comment by raphodn** [comment]
Which "pure automation" ? Calculating the completedness ? Or you were thinking of something else ?

Maybe create a dedicated issue so that we don't forget :)
