### ISSUE TITLE
Missing translations on add price 

### ISSUE THREAD

**Issue by fbtw** [openfoodfacts/open-prices-frontend#286]
### What
There are missing translations on the add price site:
single price, ticket and their descriptions.
Inside single price, the text "organic", the text "price of unit/kg"
Also on the categorizes list, all the categories are in English 

### Steps to reproduce the behavior:
1. [web app](https://prices.openfoodfacts.org/app/)
2. click on add price

### Expected behavior
the text shows translated

### Platform 
 - Platform web

![Captura desde 2024-02-05 19-55-44](https://github.com/openfoodfacts/open-prices-frontend/assets/29210382/6e5495fe-991f-4274-bdc2-52226c45e8b3)
![Captura desde 2024-02-05 19-56-57](https://github.com/openfoodfacts/open-prices-frontend/assets/29210382/b0c52d58-8892-4c31-be6f-7a4562ace379)

**Comment by raphodn** [comment]
Hi ! You didn't specify which language ?

In any case, translations are done via : https://translate.openfoodfacts.org 

Contributions welcomed :)
