### ISSUE TITLE
Bring the  Header background color in line with the other OFF projects

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#298]
### Problem
Can we change the Header background color to rgb(242, 233, 228) to bring it in line with the other OFF projects ?

### Part of
- #220

**Comment by Apurv428** [comment]
Hi @teolemon , can I take up this issue?

**Comment by raphodn** [comment]
@Apurv428 no need to ask, go for it :)

**Comment by raphodn** [comment]
1. in https://world.openfoodfacts.org/ the color seems to be `#f2e9e4` ?
2. same for the footer ?
