### ISSUE TITLE
Allow navigating to the list of prices from the proof modal

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#300]
### What

Allow navigating to the list of prices from the proof modal

### Screenshot

![image](https://github.com/openfoodfacts/open-prices-frontend/assets/1689815/9dda6368-e9fd-4abf-8a5f-4788936555d5)

**Comment by raphodn** [comment]
This would require allowing to filter prices by a `proof_id`. Slight concerns about personal info, but after all we can already filter by `owner`, and retrieve that same info :)

**Comment by raphodn** [comment]
WIP here : #375

**Comment by raphodn** [comment]
Done in #375
