### ISSUE TITLE
Create a price by day page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#301]
### Problem
- Create a price by day page so that user can look back at past prices entered at a given date.
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/1689815/65fafc03-077d-4539-afc3-7ce6c2ea5fef)

**Comment by raphodn** [comment]
Just to clarify @teolemon 
- currently we have two dates per price : the actual price date, and the added date (and time)
- your screenshot show the second one ("added date")
- if a user went to the page "prices of the 1st of January 2024", would you rather have the actual prices of that day, or the prices added that day ? 
:sweat_smile:

**Comment by serpico** [comment]
I think it's solved

**Comment by raphodn** [comment]
indeed, kinda duplicate with #672 where the PRs are linked (pages with prices per day, month, year)
