### ISSUE TITLE
Add deep-links to all 4 projects in case of "Product not found"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#323]
### What
- Add deep-links to all 4 projects in case of "Product not found"
- In those cases, the Android mobile apps will be able to pickup (and the iOS mobile app for food), and let the user proceed to product addition
- In addition, it potentially allows Open Prices to store a project tag

<img width="1413" alt="image" src="https://github.com/openfoodfacts/open-prices-frontend/assets/1689815/80a9737e-7593-4ae7-85c2-7bf4fb838cec">

**Comment by teolemon** [comment]
We could also add a button on the proof modal if the product is not found
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/1689815/5f5d1cac-69b8-4d65-8250-d6d5b61a1d2f)

**Comment by raphodn** [comment]
But only if the proof is associated to 1 price, no ?

**Comment by teolemon** [comment]
Yes, good point 👍

**Comment by raphodn** [comment]
With #522 there is a button on missing product pages, to chose between the 4 flavors

![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6cea19a8-06f8-4b44-b13c-fabbf7b493b2)
