### ISSUE TITLE
Add a "Select from existing proof" button to the Proof Addition form

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#330]
### What

Add a "Select from existing proof" button to the Proof Addition form

### Why

This single feature will allow uncoupling proof addition to price addition, which will unleash additional contributions from people who can't be bothered inputing 30 products at the same time

**Comment by dq18** [comment]
Already 3 issues on this, I guess this is very high priority! Will start on this when I have time
#153 #303

**Comment by raphodn** [comment]
Done in #376
