### ISSUE TITLE
Support setting the currency

### ISSUE THREAD

**Issue by Flaburgan** [openfoodfacts/open-prices-frontend#359]
As far as I can see, it is currently not possible to change the currency from EUR to anything else.

I quickly checked the backend and at least in the model, the currency is present: https://github.com/openfoodfacts/open-prices/blob/main/app/models.py#L130 although I'm not sure what the currencies list is containing exactly: https://github.com/openfoodfacts/open-prices/blob/main/app/enums.py#L5

I never contributed to an OFF project before, I don't know how you deal with such thing, does the backend have to tell the front-end which currencies are available, or do you want to go fast and hardcode them / load them from an external source in the front-end too?

In any case, it would be nice to see this supported.

Cheers,

**Comment by dq18** [comment]
Hi @Flaburgan ,
We first expected the user to not change currency, or rarely.
You can set the currency through the User Settings page: [settings](https://prices.openfoodfacts.org/app/settings)
Note that when choosing the country, the currency field will be automatically switched to the country currency, although you can still change it afterwards. Press "Save" and your currency will be used when adding a price.
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/21193194/3dbad6ba-cf3b-4636-bec8-0d77398d9105)

What we do need is an onboarding page with links to tutorials and for the user to setup his settings for the first time use. Similar to what is done in the OFF mobile App.

**Comment by raphodn** [comment]
@Flaburgan could you clarify and provide a screenshot (or more details) to **where** you would like to change the currency ?
- if it's when browsing the prices, then it's a conversion issue (because most of the prices are in EUR, though we have some Indian & Polish & US data)
- if it's when adding the prices, then indeed there is the possibility to change your default currency in the user settings (see answer above). it was moved there to simplify the price add form. we could have a small :information_source: tooltip to explain this to users

**Comment by Flaburgan** [comment]
@raphodn it is when adding a price. It is on EUR for me (I guess that's the default?) and I had no information how to change it. To add a tooltip could be a solution, but to be fair I don't see the link between the user and the currency. Personally, I'm crossing the border everyday so I'm constantly changing currency.

I think a smarter way to deal with this issue would be to ask for the location of the shop first (so, as the second field instead of third in the form), and then set the currency depending of it. If the shop is in the UK, in France or in Switzerland, the currency would be automatically selected.

**Comment by raphodn** [comment]
> I don't see the link between the user and the currency.

haha well to be fair, I haven't paid in another currency in... years. Not everybody lives next to a border, additionally a border with 2 different currencies :shrug: 

an alternative could be to allow the user to choose multiple "default" currencies. and in the price add form, see them appear as a dropdown.

linking the location to the currency is a good idea, but OSM data is not great to parse, we would have to do an new mapping, some countries have multiple currencies, etc...

**Comment by Flaburgan** [comment]
>in the price add form, see them appear as a dropdown.

Well that is what I was expecting opening the form, but without any default currency, just a dropdown to select it. It's not a big field, we have space to put it in the screen. Personally I would go for this solution, and would still use the location of the shop to prefill it ;)

**Comment by dq18** [comment]
I agree that the letting the user select potential currencies and have the dropdown when adding prices would be the way to go.
Along with the onboarding, that should be enough for now.

Prefill with shop location is a good idea too, I would do that on a future version, but get more user experience and design feedback first.

I also live at borders but France/Germany have the same currency. And I rarely buy in Switzerland so I haven't had the need to change yet (but should happen soon). For people traveling often, it would also help.
