### ISSUE TITLE
Page per category

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#368]
### Story

Now that we store the product's `category_tags`, we can easily filter the corresponding products of a single category.
- [ ] show the product categories on the ProductCard
- [ ] navigate to a category page
- [ ] list all corresponding products

**Comment by ArturLange** [comment]
I believe it is now done.
https://prices.openfoodfacts.org/app/categories/en:ketchup
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/10730549/8fe40f2e-e5c6-401d-8b28-508b9f2afa95)
