### ISSUE TITLE
Deleted proof takes up space

### ISSUE THREAD

**Issue by ArturLange** [openfoodfacts/open-prices-frontend#371]
### What
After deleting a proof on user's dashboard, the proof still takes up space

### Steps to reproduce the behavior:
1. Go to https://prices.openfoodfacts.org/app/dashboard/proofs
2. Delete a proof
3. Proof is deleted but still takes up space

### Expected behavior
I would expect the layout to change and for the proofs to move to a vacant space.

### Screenshots
![obraz](https://github.com/openfoodfacts/open-prices-frontend/assets/10730549/e34e9192-693a-4273-a3ed-56ed1865fdb5)

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Desktop

**Comment by raphodn** [comment]
Fixed in #378
