### ISSUE TITLE
Track if user set up Settings

### ISSUE THREAD

**Issue by dq18** [openfoodfacts/open-prices-frontend#372]
### Problem
We have no mechanism to know if a user went to the Settings page or not

### Proposed solution
- Add a boolean flag in store.js "HasDoneSettings" or similar

This would allow:
- proposing a popup /onboarding
- Additionally would avoid running guessDefaultLocale at each router.BeforeEach
- Set the default country currency if user doesn't select currency

**Comment by raphodn** [comment]
Hi @dq18 what's the underlying need ? here it seems to be already a "solution", maybe rename the issue to clarify ?
