### ISSUE TITLE
Empty "My prices" due to upper case login

### ISSUE THREAD

**Issue by ArturLange** [openfoodfacts/open-prices-frontend#415]
### What
A follow-up of #360 

Even though right now on `https://prices.openfoodfacts.org/app/users` there are no duplicated users, on `https://prices.openfoodfacts.org/app/dashboard/prices` I see no prices when I'm logged in using Uppercase login, even for prices added during that session.
When logging with lowerccase login I can see them correctly.

I also can't remove my proofs with no price with Uppercase login, but I can with lowercase login. 

### Screenshots
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/10730549/bc710095-8c40-4abe-869d-00083f9c222e)
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/10730549/6352cb90-5cb9-45fa-931e-47c68d131088)

**Comment by raphodn** [comment]
similar to #360
fixed in #491 :)
