### ISSUE TITLE
Wrong image path is used 

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#525]
### What

When selecting a recent proof on the [add multiple prices page](https://prices.openfoodfacts.org/app/add/multiple/price-tag), the wrong proof image is loaded. It always uses the image from ID [1661](https://prices.openfoodfacts.org/app/proofs/1661). However, it still selects the correct proof ID for the actual proof when you add a new price.

It seems to be because the `AddPriceMultiple-*.js` script that's loaded when you load the page, is set to always return the URL for that ID:

```
getProofUrl(o) {
            return "https://prices.openfoodfacts.org/img/0002/qU59gK8PQw.webp"
        }
```

### Steps to reproduce the behavior:
1. Go to the add multiple page
2. Select one of your recently uploaded proofs

### Expected behavior
Should load the correct proof image

### Platform (Desktop, Mobile, Hunger Games)
 - Platform Desktop

**Comment by raphodn** [comment]
Hi @odin-h thanks for the detailed bug report !

Indeed it's an oversight, I just corrected it here : https://github.com/openfoodfacts/open-prices-frontend/commit/03b7194d0c1d050f7f6478400e1686e36f51a008
