### ISSUE TITLE
Use dropdown menu instead of button to edit the currency

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#530]
### Problem
It's not apparent how you change the currency in the current edit container design. Also, using a button to open a new box requires more clicks.

### Proposed solution
Make the currency label a dropdown instead of opening a new dialogue box to change the currency. Put a dropdown menu in place of the current text label of the selected currency on the right side of the price input.

### Mockups
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/150337574/525c7a73-cb01-4623-8bbc-7f47c80f165d)

### Part of
- #402

**Comment by teolemon** [comment]
The current situation is this, and honestly it's confusing, I only knew the icon was clickable when I found this bug, after spotting a UK user adding a price in euros.
https://prices.openfoodfacts.org/app/products/4056489354079
<img width="593" alt="image" src="https://github.com/openfoodfacts/open-prices-frontend/assets/1689815/1faacd37-8fcd-4153-a89a-c3bc50ec8228">

**Comment by raphodn** [comment]
Closing as this is not in the UI anymore. Currencies can be added/edited via the Settings page
