### ISSUE TITLE
Include non-favorited currencies in the dropdown menu below your favorites

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#531]
### Problem
Having to change you preferences in order to access the other currencies on the rare occasion you have to add a price with a currency you usually don't use, seems more difficult than it should be.

### Proposed solution
Display favorite currencies at the top in the currency dropdown menu show non-favorites below. Use a grey separator line or something to let the user distinguish between the favorite currencies visually.

### Additional context
The favorited currencies could maybe instead/also have a solid star icon ⭐ to show that you've set them as favorites. Clicking the star icon could probably let you un-favorite it from the dropdown. In that case the non-favorite currencies could show a empty outlined star ☆ on the left side when you hover over them in the dropdown menu.

### Part of
- #530
- #402

**Comment by raphodn** [comment]
Closing as we chose to simplify the proof/price add form, and have the currency configuration stay on the Settings page (+ a help tooltip)
