### ISSUE TITLE
"Add more prices" button from proofs page

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#538]
### Problem
Currently the only place you can continue where you left off adding prices from an image, is on the add page.

### Proposed solutions

- [x] From the proof detail page
- [x] From the proof card : Make it possible open a proof image directly from the [proofs index](https://prices.openfoodfacts.org/app/dashboard/proofs) and redirect you to the price add page with the proof id already selected.

**Comment by Freso** [comment]
FWIW, I can currently add more prices from proofs page on desktop, but not on mobile.

**Comment by raphodn** [comment]
> FWIW, I can currently add more prices from proofs page on desktop, but not on mobile.

Indeed it doesn't seem available yet in the mobile app integration

**Comment by raphodn** [comment]
this is the frontend repo, so I'm closing this issue after #702 which adds the "Add a price" action in the proof list as well (via the ProofActionMenu)
