### ISSUE TITLE
Show preview of price per unit before upload

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#540]
### Problem
Price per kg is only displayed after uploading/editing the price.

### Proposed solution
Show a live preview of the price per unit while typing the price for products that have a known weight/quantity.

### Additional context
The price per unit field could also be editable and allow you to input the unit price instead and then automatically calculate the price per piece.

**Comment by raphodn** [comment]
Hi odin-h, I'm not sure I completely understand your request. 

The price is already correctly displayed in the form and the greyed-out feedback, no ?
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/ae8e6ea3-5f48-4ba2-8252-6f68aad78148)

**Comment by odin-h** [comment]
I mean like this, where it automatically calculates the value of the other box based on the weight while typing the price
![open prices](https://github.com/openfoodfacts/open-prices-frontend/assets/150337574/f2f6e9b8-d121-4747-b991-f7639ab081eb)
The automatic calculation would only be possible for products that have a correct weight specified. However, combining this feature with #527 could allow you to click the yellow question mark and fill in the missing/corrected weight value.
