### ISSUE TITLE
Products with 1/2 and 1/4 is added as 2 and 4

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#544]
### What
Stuff like one half and one 4th L/KG is not converted correctly. Only the last digit after the slash is kept.
Here are two examples of 0,5L cartons of chocolate milk with the quantity written as 1/2L https://prices.openfoodfacts.org/app/products/7038010002625
https://prices.openfoodfacts.org/app/products/7038010066191

### Steps to reproduce the behavior:
1. Add a product with 1/2 unit of measurement

### Expected behavior
Would be that fractions got converted to floats.

### Platform (Desktop, Mobile, Hunger Games)
 - Platform Desktop

**Comment by raphodn** [comment]
the quick fix is to edit the product quantity field directly in OFF, it doesn't seem to parse correctly the 1/X, better to change to 0,5 or 0,25 :+1:
