### ISSUE TITLE
Allow users to edit dates

### ISSUE THREAD

**Issue by TechShooter** [openfoodfacts/open-prices-frontend#552]
### What
There's no way yet to edit a price's date, other than deleting the price and adding it back

### To reproduce the behavior:
https://prices.openfoodfacts.net/app/dashboard/prices

### Expected behavior
The date should be editable

### Part of
#98

**Comment by raphodn** [comment]
Thanks for creating the issue ! The API allows to edit the date, so shouldn't be too hard to add it in the frontend :)

https://prices.openfoodfacts.org/api/docs#/Prices/update_price_api_v1_prices__price_id__patch
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/b161001a-68d6-405b-98c2-e58708039e5f)
