### ISSUE TITLE
The top bar button spans the entire screen instead of only the area you'd expect it to

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#553]
### What
The "Open Prices" button in the top bar is not limited to the width of the text/logo, which could lead you to accidentally click the "home" button when you only wanted to click the top bar to remove the focus from an input field or something.

### Steps to reproduce the behavior:
1. Go to a page that is not the [home page](https://prices.openfoodfacts.org/app/) e.g. the [latest prices page](https://prices.openfoodfacts.org/app/prices).
2. Click a part of the top bar that's not on the Open Prices logo or text.
3. Get taken to the home page despite not clicking where the button is displayed in the UI.

### Expected behavior
Only the area with the logo and text of the top bar should act as the button. Clicking this button should maybe also prompt the user to confirm using the `onbeforeunload` event listener if you have unsaved work. Like when adding new prices.

### Screenshots
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/150337574/ba95f8aa-e45f-4d92-9545-acf588637f56)

### Platform (Desktop, Mobile, Hunger Games)
 - Platform Desktop

### Part of
-

**Comment by raphodn** [comment]
I see, fixed :+1:

**Comment by raphodn** [comment]
When clicking in the space between the blank spaces, do you expect a behavior ? like scrolling to the top ?

**Comment by odin-h** [comment]
No, not really. Just found myself accidentally clicking it way too often when trying to change window and such.
