### ISSUE TITLE
Inputing new price via category instead of barcode : limited choices

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#570]
### Problem
use case 1 : bulk purchase for pulses, sold per weight, tried red bean/haricots rouges, chick pea/pois chiches but not found.
use case 2 : I have a receipt with 6 different kinds of meat with prices per kg I purchased 2 years ago, as I'm a regular in this butcher shop I'd like to be able to track the evolution of prices since they've been offering the same products for years. 

### Additional context
https://github.com/openfoodfacts/open-prices/assets/1227077/69c9b2f6-1b58-459d-b79f-1404492581e6
what about pulse day ? :smile:

**Comment by raphodn** [comment]
Hi @serpico ! I moved your issue to the frontend repo :)

I think it's a bit of a duplicate with #262, no ? you can leave your comment there. And indeed we have still quite a lot of "categories" missing

**Comment by raphodn** [comment]
I'm closing in favor of #262
You can list the missing categories (or parent categories) there !
