### ISSUE TITLE
Dashboard stuck at 0 prices ( number of proofs ok ) while userpage showing plausible number of prices and updating

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#571]
### What
Main bother is there's no `PriceActionMenuButton` displayed to edit/delete prices or proofs

### Platform (Desktop, Mobile, Hunger Games)
- Both on mobile Android 5 using up-to-date Fennec browser and Desktop Firefox 125.0.3

**Comment by raphodn** [comment]
Hi @serpico , can you try to log out and log in again ?

It seems to be an old bug, that I think we solved. see #360

**Comment by serpico** [comment]
I tried ( on both mobile and desktop ) I think my initial username was lowercase, I tried using Uppercase see if it would change something but it's like it's forcing the lowercase.

After your message I logged in with a different browser's profile, so as to avoid something related to password manager, using lowercase but to no avail, still 0 prices in dashboard.

**Comment by raphodn** [comment]
Is it still an issue ?

**Comment by serpico** [comment]
Thanks a lot for following up.

It's even worse :) 

Prices were always 0 and a couple days ago or last week proof went to 0  see screenshots from webapp and smoothie.

In smoothie, I'm not sure there supposed to be a number next to My proofs as there is one next to My price, but I can see my proofs and prices when I tap on the respective buttons.

![0proof](https://github.com/user-attachments/assets/1a110c5b-9715-4d75-8dca-bdf849e52af1)
![smoothie](https://github.com/user-attachments/assets/8a799362-f387-42ad-8d7a-e43ca6b4e978)

I browsed a few issues about editing prices, changing locations, etc...some of them were solved, I poked around the UI in the webapp to see if I could find some menu in webapp to edit my prices but could find any ( can you post a screenshot if there is/are, indeed, menu(s) ? to change date, change location of price, etc )...and also thought maybe it's related if the webapp consider I have 0 price it makes sense that I'm not allowed to edit/modify/delete any.

**Comment by raphodn** [comment]
and same on mobile ? it could also be a browser cookie issue.
I really don't know..

in https://prices.openfoodfacts.org/app/dashboard/prices the uderlying API query is
```
https://prices.openfoodfacts.org/api/v1/prices?app_name=Open+Prices+Web+App&page=1&size=20&order_by=-created&owner=serpicozaure
```

**Comment by serpico** [comment]
For the record, here are the screenshots on mobile, I'll try to log in with a different computer in a few weeks, see if that changes anything.

![Screenshot_20240923-175351](https://github.com/user-attachments/assets/ee7c3cca-d63e-4c67-b3ba-a4bae8a3b544)
![Screenshot_20240923-175435](https://github.com/user-attachments/assets/5076374a-ae19-4d6d-892a-84da794075e5)

**Comment by raphodn** [comment]
ok the big issue here is your email showing up, it should be your username.
sorry for asking again, but did you try to log out, and log back in (with your username, not your email) ?

**Comment by serpico** [comment]
Don't apologize, all the less since you solved the issue :)
I don't know if I didn't understand the first time, anyway I thought they were interchangeable.
Now it shows a coherent number of proofs and prices.
 Thanks for your patience.

**Comment by raphodn** [comment]
keycloak is coming soon - https://github.com/openfoodfacts/openfoodfacts-auth - it should simplify this in the future !
