### ISSUE TITLE
OFF product discrepancy

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/open-prices-frontend#587]
### What
I entered a price with Smoothie for product 7300400482844.
This product is recognized by Smoothie.
It's labeled "unknown" by the Prices web app.

### Steps to reproduce the behavior:
1. Go to https://prices.openfoodfacts.org/app/search
2. Look for `7300400482844`
3. The product is unknown (but has prices)
4. The product exists in OFF, though - https://fr.openfoodfacts.org/produit/7300400482844/wasa-tartine-croustillante-complet-260g

### Expected behavior
The product should be found in OFF and displayed correctly in Prices.

### Screenshots
![image](https://github.com/openfoodfacts/open-prices-frontend/assets/11576431/f168f918-bb48-4104-99e0-a09ef2a026be)

**Comment by teolemon** [comment]
There's a lag since we have a local copy of the db

**Comment by monsieurtanuki** [comment]
> There's a lag since we have a local copy of the db

I can understand that, but it's not a new product (in the OFF db since April 2022) and it already had a price from 8 weeks ago.

**Comment by raphodn** [comment]
the issue here is that the product is "obsolete"

![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/aec7c95e-d089-44c5-8b1c-087fd70d1b2f)

Known problem, see this issue in the backend : https://github.com/openfoodfacts/open-prices/issues/281 (we need to find a way to sync these products as well)

**Comment by monsieurtanuki** [comment]
Then there's a minor data problem in the OFF database as this "obsolete" product can be purchased today.

**Comment by serpico** [comment]
Additionally, not all obsolete products seems to be handled the same.

- `3414280971108` while obsolete in OFF is rendered fine in OP ( I bought it recently ).
- `3596710430161` also obsolete in OFF ( with an additional withdrawal date ) is rendered partially in OP.

**Comment by monsieurtanuki** [comment]
For French people only...

Je propose qu'on fasse passer le champ `obsolete` en type `perceval` qui n'a qu'une seule valeur possible : `"C'est pas faux !"`
Source : https://m.facebook.com/allocine/videos/sc%C3%A8ne-culte-kaamelott/207254386821697/?locale=fr_FR

**Comment by raphodn** [comment]
Closing in favor of the backend issue https://github.com/openfoodfacts/open-prices/issues/281 :+1:
