### ISSUE TITLE
Page per location

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#59]
### Story

Allow the user to navigate to a given location, and see info such as:
- location details (name, address, map)
- most recent prices

**Comment by teolemon** [comment]
I was wondering about having a Distributor page, that would cluster locations, and a Brand page as well. 

That could also be an occasion to start crowd sourcing information about locations, writing back to Open Street Maps, and about brands, writing back either to Wikidata, or an Open Food Facts specific backend. 

Everything would look slicker with logos.

**Comment by raphodn** [comment]
Yes it would be great to have clean taxonomies for distributors and brands !
