### ISSUE TITLE
Allow contributors to edit location of prices they submitted in case of mistake or bug

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#599]
### Problem
For different reasons the location for price can be wrong ( limitation of location picking process, forgetfulness )

### Additional context
Several prices where attributed to `https://prices.openfoodfacts.org/app/locations/420` while it should have been attributed to `https://www.openstreetmap.org/node/252814154`, as far as I know it's not possible for the proof owner to correct that ( although because of #571 I can't be sure ).

### Part of
- #

**Comment by raphodn** [comment]
Closing in favor of #879 (we will only allow users to edit the price's proof)
