### ISSUE TITLE
Improve location search (alternative to Nominatim ?)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#61]
### Story

In the location selector we use Nominatim "reverse geocoding" for the search results. But the results are sometimes disapointing or missing.

Example : "casino saint flour" returns 0 results, even though there are a couple of "Petit Casino" in and around.

### Alternatives

https://wiki.openstreetmap.org/wiki/Geocoding

|Name|Link|Comments|
|---|---|---|
|Nominatim|https://wiki.openstreetmap.org/wiki/Nominatim|Currently used|
|Photon (Komoot)|https://photon.komoot.io/|looks good !|
|OSM POI (addok)|https://github.com/osm-fr/osmpoi4addok||
|Other ?|||

wiki page with more details : https://github.com/openfoodfacts/open-prices-frontend/wiki/Location-search

**Comment by teolemon** [comment]
We could focus on the brands, and remove extra words like petit.
Alternatively we should find a fuzzy match alternative.
The discussion on the nominatim side seems stalled: https://github.com/osm-search/Nominatim/issues/759

**Comment by raphodn** [comment]
Photon seems based on ElasticSearch, i tried it and got much better results

**Comment by raphodn** [comment]
I created a wiki page to add more details for each location search engine : https://github.com/openfoodfacts/open-prices-frontend/wiki/Location-search

and I opened a PR to replace Nominatim with Photon

**Comment by monsieurtanuki** [comment]
@raphodn Photon looks very good indeed!

**Comment by raphodn** [comment]
Reminder of current limitations with our Location search
- the "full text search" is done with Photon (free online service): https://photon.komoot.io/
- the Photon API data is synced with OpenStreetMap every tuesdays (mentionned here: https://github.com/komoot/photon/issues/614)
- an alternative is to search by OSM ID, which uses another API: Nominatim. It takes a few minutes to sync (if you created a new node)

What I do when a node is missing
- open OpenstreetMap.org on my browser
- double check that the POI (node or way or relation) is indeed non-existant
- create it + save
- get its newly created ID
- wait a few minutes & search by ID directly
- or wait until next tuesday ^^
