### ISSUE TITLE
What happen with invalid barcode's products ?

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#626]
### What

Following the recent changes I noticed `356470000122603` which I think is probably `3564700001226` ( based on the price, location, etc...+ I ended up looking at the proof and it seemed even more plausible ). What is supposed to happen in these cases ? ( products get purged after some time, there will be a reconciliation process somewhere down the line one day, ...) I'm just curious :)

**Comment by raphodn** [comment]
Linked to #533

https://prices.openfoodfacts.org/app/products/356470000122603
ah i see a bug in the display

> What is supposed to happen in these cases ?
Nothing for now. but we should have some kind of moderation, and allow admins to edit the product code

**Comment by raphodn** [comment]
added a line in the discussion here : https://github.com/openfoodfacts/open-prices/discussions/319
