### ISSUE TITLE
Proof: link a date, location & currency

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#634]
### Story

In the backend we're adding new fields to the `Proof` model
- date : https://github.com/openfoodfacts/open-prices/issues/322
- location : https://github.com/openfoodfacts/open-prices/issues/323
- currency : https://github.com/openfoodfacts/open-prices/issues/336

We can now improve the price add form to ask first for the proof + date + location + currency.
This will simplify price addition afterwards (pre-fill form, quality check on price data, ...)

This is valid for `RECEIPT` & `PRICE_TAG` proofs

**Comment by teolemon** [comment]
Next, we need Open Prices to aggressively nudge you if you haven't inputed prices on all of your receipts :-)

**Comment by raphodn** [comment]
Closing as this done in the web frontend.

Hopefully it will be integrated soon in the mobile app :pray:

**Comment by monsieurtanuki** [comment]
@raphodn Already coded in off-dart (https://github.com/openfoodfacts/openfoodfacts-dart/pull/946) and Smoothie (https://github.com/openfoodfacts/smooth-app/pull/5480)

**Comment by raphodn** [comment]
> @raphodn Already coded in off-dart and Smoothie

ok ! what got me confused is that its not yet in the released mobile app, as i still new proofs without this info :eyes:
