### ISSUE TITLE
Allow sorting latest prices reverse chronologically, or filter per year

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#672]
### Problem
- We now have cool price points from 2010. 
- I'd like us to surface them (that's a unique selling point)

### Possible solutions
- Allow sorting latest prices reverse chronologically, or filter per year
- create a price-added/2010-02 facet

### Part of
- #220

**Comment by raphodn** [comment]
Started working on this : 
- added a backend price filter by date year & month : https://github.com/openfoodfacts/open-prices/pull/350
- added a frontend page per date `/dates/YYYY-MM-DD`

Next up : 
- a frontend page per month : `/dates/YYYY-MM`
- a fronend page per year : `/dates/YYYY`

**Comment by raphodn** [comment]
Deploying ! Not yet findable for end users, but the urls above show the prices for a given date / month / year

**Comment by raphodn** [comment]
made some changes in #687 to better display the price date. the user can click on the chip to access the prices for the given date
