### ISSUE TITLE
proof upload error

### ISSUE THREAD

**Issue by Dambond** [openfoodfacts/open-prices-frontend#684]
### What
 cant upload proof

### Steps to reproduce the behavior:
1. Ajouter un seul prix
2. immage ou gallerie de l'appareil
3. click on téléverser
4. error when creating proof
![IMG_20240713_174502](https://github.com/user-attachments/assets/549503e8-8534-4625-a6b3-980fd9bed7f5)

### Platform (Desktop, Mobile, Hunger Games)
 - OS:  /e/os 1.19.1-s-20240111372761-dev-beyond0lte
 - Platform  mobile firefox

### Part of
- 
![Screenshot_20240714-091305_Firefox](https://github.com/user-attachments/assets/2d18dfbf-3907-4a7a-aac6-d14c22424340)

**Comment by raphodn** [comment]
Hi @Dambond thanks for reporting the issue with such details.
I had the problem yesterday as well.

I checked Sentry this morning, the error is due to a lack of space on the server.

I notified it on Slack, hopefully it will be solved soon ! cc @teolemon

**Comment by teolemon** [comment]
@alexgarel
