### ISSUE TITLE
Proof: allow editing proofs with prices

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#689]
### What
I cannot update nor delete any proof using the web app.
I tried to log in and out, but it didn't change anything.

### Steps to reproduce the behavior:
1. Log in as my user (raphael0202)
2. Go to proof dashboard
3. Try to delete a prood

### Screenshots
![Screenshot_2024-07-22-15-44-56-19_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/user-attachments/assets/85af357b-1f77-458b-a008-df7d81b2beb5)

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Android
 - Platform: web

**Comment by raphodn** [comment]
Indeed for now users can only edit / delete proofs without prices.
One of the reasons : if you edit the proof date, the change isn't yet replicated on the price dates.

**Comment by raphael0202** [comment]
>  One of the reasons : if you edit the proof date, the change isn't yet replicated on the price dates.

Can't we trigger the update on the backend?

**Comment by raphodn** [comment]
> Can't we trigger the update on the backend?

yes of course :) not yet done to simplify. created an issue in the backend : https://github.com/openfoodfacts/open-prices/issues/396

**Comment by raphodn** [comment]
Changes were made in the backend to update prices once a proof is updated ✅ 
And thanks to https://github.com/openfoodfacts/open-prices-frontend/commit/72a4ef5f1764e9a921ab6b38efffe6f2942214c6 I made the change to allow a user to edit all of its proofs (with or without prices).
