### ISSUE TITLE
Spelling mistake spotted in the french privacy warning

### ISSUE THREAD

**Issue by jusdekiwi** [openfoodfacts/open-prices-frontend#835]
### What
It is missing n' in the first sentence after the two items listed.

### Steps to reproduce the behavior:
Submit a price on the mobile app.

### Expected behavior
Si vous êtes pas à l'aise -> Si vous n'êtes pas à l'aise

### Screenshots
![458608275_1514798665807861_2220876931414494854_n](https://github.com/user-attachments/assets/ba4aee49-39c4-4526-a9dc-35eb4e014667)

**Comment by raphodn** [comment]
Hi @jusdekiwi !

The translations happens on https://crowdin.com/project/openfoodfacts ;)
Feel free to correct it there :pray:
