### ISSUE TITLE
Single price add : "Select a recent proof" don't seem to work anymore

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#838]
### What
When I click on the "Select a recent proof" button a window show up but no proof shows up/no way to pick a proof

### Steps to reproduce the behavior:
1. Go to Search
2. Type `3104544071506`
3. Click on the "3 stacked dots" button and select "Add a price"
4. Click on the "Select a recent proof" button
5. A very small height window appear but there's no proof to pick from

### Screenshots
![Capture d’écran_2024-09-23_14-04-57](https://github.com/user-attachments/assets/ec0a18aa-06c6-4b0d-a04e-b1fccebd7415)

### Platform (Desktop, Mobile, Hunger Games)
 Xubuntu ; Firefox 130.0.1

**Comment by raphodn** [comment]
ah interesting, you're using the SinglePriceAdd workflow :)
I believe it's the only way to get access to this page now, following #636

Is it a page you want to see maintained ?
Going through the proof first, and scanning (or typing) the barcode, would work in your case or not ? (Multiple price add workflow, now the default)

**Comment by raphodn** [comment]
Regarding your issue, I just tried to reproduce (thanks for the detailed steps, super helpful :pray: ), and I did not have a problem (the modal did take a bit of time to load, but it's more of a issue regarding image size - in my todo to have multiple image sizes in the backend)

**Comment by raphodn** [comment]
if you are on a desktop browser, maybe there's errors in your browser console ?

**Comment by serpico** [comment]
To tell you the whole truth :) I saw and added the price for `3104544071506` today, thinking "I bought that stuff a few years ago, I wonder if it's on one my proofs in OP" then thanks to https://github.com/tasks I was able to pin down the date which led me to https://prices.openfoodfacts.org/app/prices/25597 if you look at the proof ( can you still ? with the recent updates ) it's there, you'll see the designation match "Manchons de canard..." ( and Task also concur on the EAN ).

So I wanted to add the old ( 19/10/2021 ) price and that's how I ended using that "workflow" as I didn't know how to "link" old proof to price I want to add, maybe you have some advice for me on how best to proceed in this particular case ?

Now to answer your question, I have a txt file with the all the EAN of the products I track so for pictures of single price tag/single product ( 1 proof 1 price ), I copy/paste from this file into the search field and off I go...

I should be able to change my way of doing and start with uploading the proof using Multiple price add workflow.

For the recent proof seemingly not loading/showing up on my side I'll retry, give it some time to load and dig into the browser console to try and see something if it still doesn't work.

**Comment by raphodn** [comment]
The "select a recent proof" modal is tailored for getting a "recent" proof.
The alternative (that I often use) is to go to https://prices.openfoodfacts.org/app/dashboard/proofs and select the proof you want.

In your case, with hundreds of proofs already uploaded, it is definitely tricky (and slow/impossible) de find it. Allowing to filter by year/month/day ? By shop/city/country ?

**Comment by serpico** [comment]
Something like https://prices.openfoodfacts.org/app/dates/2021-10-19 but for proof might do the trick.
But I agree it's kinda of niche thing and, in my case,  considering #571 it probably wouldn't work anyway.
I'll try to be careful and refrain from reporting issues that might be related to proofs and the fact that I might not have real "ownership" to them as this time.

Should I close the issue ? since it works for you and the title doesn't even match the feature of digging through old proofs to link one to a price several months/years later.

**Comment by raphodn** [comment]
ok ! I created an issue for the proof dashboard filters #839
