### ISSUE TITLE
On categories page, choosing another category doesn't properly refresh the list

### ISSUE THREAD

**Issue by TTalex** [openfoodfacts/open-prices-frontend#841]
### What
On categories page, choosing another category doesn't properly refresh the list

### Steps to reproduce the behavior:
1. Go to a category page https://prices.openfoodfacts.org/app/categories/en:spices
2. Display the other categories of a product
3. Choose another category

### Expected behavior
The list should be updated with the new category.
Instead, the previous category is still used (the url changes though, and refreshing fixes it)

### Screenshots
![cat_change](https://github.com/user-attachments/assets/be98fe67-adc2-4f93-8ebc-e7f6c30cb22d)

### Platform
Firefox 130.0.1 (64-bit) on Ubuntu 20.04

**Comment by raphodn** [comment]
thanks for the details bug report and video and PR :100:
