### ISSUE TITLE
New page that lists/showcases data re-use

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#842]
### Story

For instance https://dmayaux.shinyapps.io/open_prices/ (#764)

### How

Where to store this list ?
- in the backend + API endpoint (but hard for people to contribute)
- in a YAML or JSON file in the backend repo + called/parsed by the frontend (why the backend ? where the "data/API" is)

**Comment by teolemon** [comment]
<img width="941" height="536" alt="Image" src="https://github.com/user-attachments/assets/c92364ae-08c7-45ca-8dd2-a2da3593c261" />
