### ISSUE TITLE
Add all potatoe categories

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#87]
Potatoe categories are missing: https://world.openfoodfacts.org/category/potatoes

**Comment by teolemon** [comment]
Related, it would be nice to use wikidata to fetch photos of categories.

**Comment by raphodn** [comment]
@raphael0202 how did you generate the initial categories json ?

**Comment by raphael0202** [comment]
With a script, by fetching all subcategories under "fruits" and "vegetables", with an additional manual curation step.

**Comment by raphodn** [comment]
Ginger missing as well ?
