### ISSUE TITLE
Fix the relative time displayed (server timezone ?)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#877]
### Story

New prices always show at least "2h" ago, when they should show "Xs" ago or "Xm" ago :)

### Example

Creating this issue at 9:52 AM (French time).
The latest price's relative time shows up with "3h" ago
The latest price's raw timestamp is `2024-09-30T06:38:14.855888Z`
The latest price's tooltip displays 8:38AM

![image](https://github.com/user-attachments/assets/48faa9b9-32c4-414c-91b3-88f1987226db)

**Comment by TTalex** [comment]
Assuming the server replies in UTC (it should be, since Z is used in the raw timestamp string), #880 should fix this.
