### ISSUE TITLE
Revamp the personal dashboard page

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#878]
### Story

As discussed during the OFF days, we should try to show more interesting personal data to the logged-in user.

### Ideas

...

### Todo

...

### Linked issues

- #843 
- #866 
- #839

**Comment by serpico** [comment]
- It's not exactly the [use case](https://github.com/openfoodfacts/open-prices-frontend/issues/866#issuecomment-2381387631) case mentioned by @teolemon in which the "uncompleted" receipt is at the center but I got the price tag picture ( 1 price ) already uploaded but the product is not in the taxonomy yet ( but should be soon IIUC ) if I upload other proofs in the meantime, the "missing product in the taxo" one will get buried ( similar to #839 ) so at least some kind of "favorite/starred" proof system could help in that specific case, uncompleted receipt, won't as there's a chance I got many so the burying will still happen.

- List feature ( maybe only within the process of integration with smoothie, I don't know enough about the technical process to see how it should progress ), quick link to access a list mixing products ( with amount ) to be picked up (shopping list ) and list of tracked products ( not to be be bought ), just to take picture of price tags to update the price during downtime. A checkbox/strike through action for each item/product would be useful, as the shopping session progress.

**Comment by raphodn** [comment]
> missing product in the taxo

I feel this is one (of many) "quality tag" that could be generated and stored for each price.
It could then be one of the filters available

Examples: product unknown, category unknown, discount missing full price, price strange (if too far off the mean ?), ...

**Comment by raphodn** [comment]
In #1179 I added some extra stats displaying today's price/proof upload counts

**Comment by raphodn** [comment]
We need a new revamp 😅 

On the matter of clearly differentiating "owned" proofs/prices (consumption-related) and "community" proofs/prices (price tags).

cc @TTalex
