### ISSUE TITLE
Prefill the last scanned barcode into the 'type manually' barcode field

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#918]
### Problem
When the scanner reads a barcode incorrectly with only a few digits being incorrect, you still have to retype the whole barcode again when choosing the type manually option

### Proposed solution
Prefill the last scanned barcode into the type manually field so you can fix incorrect digits instead of having to retype the whole code.

### Additional context
The pre-filled barcode should probably be fully highlighted when the input box opens in case the user decides to start typing right away, not expecting there to be a pre-filled value there. That way it will be replaced when they don't intend to edit the existing value.

### Part of
- #

**Comment by raphodn** [comment]
I regularly face the same problem, good idea :)

I'm wondering if could have different solutions : 
- we could suggest the last "typed" price above, and the user could click to have it pre-filled
- should we only suggest on retype, or even after a successful price has been added ? (sometimes it's the same producer, and the number is almost identical)
