### ISSUE TITLE
Despite #808 it's still possible to create prices for location which are neither shop nor amenity

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#937]
### What
See https://prices.openfoodfacts.org/locations/1173

Linked to #808 
Related to https://github.com/openfoodfacts/smooth-app/issues/5568

**Comment by raphodn** [comment]
Added via the web or mobile ? For the web it shouldn't be the case

**Comment by serpico** [comment]
No idea. I just saw it on "Latest prices", followed the OSM link and opened the issue. Is there a way for a regular user to check this (web or mobile ) something similar to a of user agent ?

**Comment by raphodn** [comment]
Ok i see, yeah the previous mobile version has this issue. Though I'm not even sure if the latest has this fixed or not. 

(Another issue with the previous mobile app is the proofs without location/date/currency, working on a PR to fix this every night)

**Comment by raphodn** [comment]
Related issue: https://github.com/openfoodfacts/smooth-app/issues/5568

**Comment by raphodn** [comment]
And we do store the user agent (actually a url param), but it's not made available via the API i think

**Comment by raphodn** [comment]
actually we don't store the app version 😬 

![Image](https://github.com/user-attachments/assets/8a03abe9-f64d-4c70-8ec9-614bae4b240a)

--> https://github.com/openfoodfacts/open-prices/issues/502

**Comment by raphodn** [comment]
Closing as this is a mobile problem + we now store the app_version :)
