### ISSUE TITLE
Bring back the possibility to upload an existing picture as proof on mobile

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices-frontend#94]
It used to be possible to upload an existing picture as proof on mobile. It's not available anymore, to make price upload more efficient.
However, it prevents taking a bunch of photos and uploading prices after, which is the way I proceed in supermarkets.

We can add a settings page where it's possible to activate the "fast mode" for those who never upload existing proof images.

**Comment by raphodn** [comment]
@raphael0202 but how do you scan the product when you're at home ? or is this use-case only for non-barcode products ?

**Comment by raphael0202** [comment]
Yes it's mostly for raw products, but it can make sense too when the product can be found easily in DB. Allowing to add the barcode field back would be nice too in that regard.
