### ISSUE TITLE
Recent flood of duplicates

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#951]
### What
Examples includes :

https://prices.openfoodfacts.org/products/0627735262420
https://prices.openfoodfacts.org/products/4001743019201
https://prices.openfoodfacts.org/products/8422584091168

**Comment by raphodn** [comment]
Thanks for creating the issue, we're on it :)
- https://github.com/openfoodfacts/smooth-app/issues/5689
- https://github.com/openfoodfacts/open-prices/issues/422
