### ISSUE TITLE
Status of proof editing ?

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#984]
Epic: #

### Description
I was playing around my proofs, got to try the "Hide proofs with prices" filter which worked beautifully and then got to a specific proof which had no date, no location, no currency ( probably no type either but I can't be sure...), I tried the edit option and changed all I could except there was no field to input/search for location, is this a known issue ?
 
### Notes
The new fields _Total amount_ and _number of prices_ worked perfectly as well.

**Comment by raphodn** [comment]
I have 3h of train tonight, I plan on diving in the proof location edit bit :)

**Comment by raphodn** [comment]
For proofs without location/date/currency (coming from old mobile versions), there's a script that would fix them if they have at least 1 price. But for the ones without prices the edit form is indeed the only option. And the location edit is the last thing missing...

**Comment by raphodn** [comment]
Closing in favor of #689 & #879
